server:
  port: 8083

spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  sql:
    init:
      mode: always
  data:
    jdbc:
      dialect: h2

grpc:
  server:
    port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
